/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_haodl_ndk_MainActivity */

#ifndef _Included_net_haodl_ndk_MainActivity
#define _Included_net_haodl_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_haodl_ndk_MainActivity
 * Method:    helloWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring; JNICALL Java_net_haodl_ndk_MainActivity_helloWord
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
